name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.58.0-noble

    strategy:
      matrix:
        node-version: [24.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Initialize submodules
        run: git submodule update --init
      - name: Install dependencies
        run: npm ci
      - name: ESLint
        run: npm run lint:check
      - name: Prettier
        run: npm run format:check
      - name: Build
        run: npm run build
      - if: matrix.node-version != '22.x'
        name: Tests
        run: npm test
      - if: matrix.node-version == '22.x'
        name: Tests with coverage
        run: npm run test:coverage
      - if: matrix.node-version == '22.x'
        name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
