name: Publish to npm

on:
  push:
    tags:
      - "v*.*.*"   # v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: git submodule update --init
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run lint:check
      - run: npm run format:check
      - run: npm run build
      - run: npm test
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}        
