name: Release Please
on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for OIDC
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          token: ${{ secrets.GH_TOKEN }}

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - run: git submodule update --init
        if: ${{ steps.release.outputs.release_created }}

      - uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org'

      - run: npm install -g npm@latest
        if: ${{ steps.release.outputs.release_created }}

      - run: npm ci
        if: ${{ steps.release.outputs.release_created }}

      - run: npx playwright install --with-deps
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run lint:check
        if: ${{ steps.release.outputs.release_created }}

      - run: npm run format:check
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish --verbose # runs both build & tests in prepublishOnly script
        if: ${{ steps.release.outputs.release_created }}
